import { ArrowRight, ArrowUpRight, CalendarDays, Check, CircleDollarSign, ClipboardCheck, FileText, ShieldCheck, UsersRound } from "lucide-react";
import { useState, type FormEvent } from "react";
import { PublicShell, marketingWidth as wrap, marketingAction as action, marketingHeading as heading } from "../components/PublicShell";

export type PublicPageId = "about" | "ndis" | "ai" | "security" | "contact";
interface PublicPageProps { page: PublicPageId; onNavigate: (page: "home" | PublicPageId) => void; onGetStarted: () => void; onSignIn: () => void; }
const content = {
  ai: { label: "The Provider.ai platform", title: "The everyday work. All together.", description: "One operating workspace for small and medium NDIS providers. Manage your participants, workforce, roster, finance and quality without losing the context between them." },
  ndis: { label: "For small & medium NDIS providers", title: "Built for your kind of busy.", description: "You need a clear view of your services, staff and business. Provider.ai brings those moving parts together for teams delivering community participation and in-home support." },
  about: { label: "Why Provider.ai", title: "Good care deserves better tools.", description: "Small and medium providers carry big responsibilities. We’re building a simpler way to manage the work behind care, with people and their judgment at the centre." },
  security: { label: "Trust & security", title: "Care starts with trust.", description: "Participant information deserves thoughtful handling. Provider.ai’s approach starts with controlled access, clear ownership and visible records of important activity." },
  contact: { label: "Your next step", title: "Start with your working day.", description: "Tell us about your provider, the systems you use and the work that takes too much time. A clear picture is the first step towards a better workspace." },
};
const features = [
  { icon: UsersRound, title: "Participant management", text: "Profiles, plans, goals, agreements and support needs in one record." },
  { icon: CalendarDays, title: "Workforce & rostering", text: "Worker information, credentials, availability and service schedules." },
  { icon: CircleDollarSign, title: "Finance operations", text: "Timesheet review, payroll preparation, invoices and claim work." },
  { icon: ShieldCheck, title: "Quality & compliance", text: "Incidents, evidence, review tasks and the details that need attention." },
  { icon: ClipboardCheck, title: "Recruitment & onboarding", text: "Jobs, candidates and the transition from accepted offer to your workforce." },
  { icon: FileText, title: "Reports & settings", text: "Operational exports, organisation settings and permitted access." },
];

export function PublicPage({ page, onNavigate, onGetStarted, onSignIn }: PublicPageProps) {
  const current = content[page];
  const [notice, setNotice] = useState("");
  const prepareEnquiry = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = Object.fromEntries(new FormData(event.currentTarget));
    const text = Object.entries(data).map(([key, value]) => `${key}: ${value}`).join("\n");
    try { await navigator.clipboard.writeText(text); setNotice("Your enquiry has been copied. Online delivery is not connected yet; no message has been sent."); }
    catch { setNotice("Your browser could not copy the enquiry. Please copy the details manually. No message has been sent."); }
  };
  return <PublicShell page={page} onNavigate={onNavigate} onGetStarted={onGetStarted} onSignIn={onSignIn}>
    <section className={`${wrap} pb-16 pt-16 sm:pb-20 sm:pt-20`}><p className="mb-6 text-sm text-brand-700">{current.label}</p><h1 className="max-w-[900px] text-[clamp(42px,5.5vw,68px)] font-medium leading-[1.06] tracking-[-.055em] text-ink">{current.title}</h1><p className="mt-7 max-w-[650px] text-base leading-8 text-muted">{current.description}</p>{page !== 'contact' && <button className={`${action} mt-8`} onClick={onGetStarted}>Explore the workspace <ArrowUpRight size={17} /></button>}</section>

    {page === "ai" && <section className={`${wrap} pb-20`}><div className="mb-12 overflow-hidden rounded-xl border border-line bg-white"><img src="/product/workspace.png" alt="Provider.ai dashboard showing fictional services, summaries and attention items" className="w-full" /><p className="border-t border-line px-5 py-3 text-xs text-muted">Actual product preview · Example data</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(({icon: Icon, title, text}) => <article key={title} className="rounded-xl border border-line bg-white p-7"><span className="grid size-11 place-items-center rounded-xl bg-canvas"><Icon size={21} strokeWidth={1.4} /></span><h2 className="mb-3 mt-6 text-xl font-medium text-ink">{title}</h2><p className="text-sm leading-7 text-muted">{text}</p></article>)}</div></section>}

    {page === "ndis" && <section className={`${wrap} pb-20`}><div className="grid gap-4 md:grid-cols-3">{[["A small team", "Keep the essentials in one place", "Stay across participants, workers and upcoming services without making the owner the only person who knows where things stand."], ["A growing provider", "Give each team a clear view", "Let roster coordinators, service managers and finance teams work from the same operational context, with access appropriate to their role."], ["A busy service", "Keep the day moving", "Bring open shifts, outstanding reviews and important records into view so your team can focus on the next action."]].map(([label, title, text]) => <article key={label} className="rounded-xl border border-line bg-white p-8"><p className="text-xs text-brand-700">{label}</p><h2 className="mb-4 mt-8 text-2xl font-medium leading-tight text-ink">{title}</h2><p className="text-sm leading-7 text-muted">{text}</p></article>)}</div><div className="mt-12 rounded-xl bg-brand-100 p-8 sm:p-10"><h2 className="text-2xl font-medium text-ink">Built around care, with your team in control.</h2><p className="mt-4 max-w-[750px] text-sm leading-7 text-muted">Provider.ai supports operational work. It does not replace professional judgment, your accounting or certified payroll systems, or your responsibilities as an NDIS provider.</p></div></section>}

    {page === "about" && <section className={`${wrap} grid gap-12 border-t border-line py-16 md:grid-cols-2`}><h2 className={heading}>Less time managing systems.<br />More time running your service.</h2><div className="space-y-6 text-base leading-8 text-muted"><p>A participant plan, a worker credential and an invoice may live in different tools, but they are parts of the same service. When that connection gets lost, teams spend time finding information and rebuilding the story.</p><p>Provider.ai is being built to bring that work together. Our focus is small and medium Australian NDIS providers: teams that need useful, comprehensive software without an enterprise implementation team.</p><p>Clear information. Practical workflows. Human oversight. Those principles guide what we build.</p></div></section>}

    {page === "security" && <section className={`${wrap} pb-20`}><div className="grid gap-4 md:grid-cols-3">{[["Access with a purpose", "Organisation boundaries and role-based access help keep workspace information with the people permitted to use it."], ["A visible record", "Important actions need clear ownership and an activity history. Evidence should stay connected to the work it supports."], ["People remain responsible", "Assistance should explain its sources and limitations. Sensitive decisions belong with authorised people, not an unattended assistant."]].map(([title, copy]) => <article key={title} className="rounded-xl border border-line bg-white p-8"><ShieldCheck className="size-6 text-brand-700" strokeWidth={1.5} /><h2 className="mb-4 mt-7 text-xl font-medium text-ink">{title}</h2><p className="text-sm leading-7 text-muted">{copy}</p></article>)}</div><p className="mt-7 max-w-[800px] text-sm leading-7 text-muted">Production deployment details, data hosting, retention, authentication controls and supported integrations must be confirmed for your organisation before live participant data is used. This page describes the product approach, not a certification or guarantee of compliance.</p></section>}

    {page === "contact" && <section className={`${wrap} grid gap-10 pb-20 lg:grid-cols-[.8fr_1.2fr]`}><div><h2 className="text-2xl font-medium text-ink">Let’s understand your provider.</h2><p className="mt-4 text-sm leading-7 text-muted">Start with your team size, the supports you deliver, and the tasks that take the most effort.</p><div className="mt-8 rounded-xl border border-line bg-white p-6"><h3 className="text-base font-medium text-ink">Prefer to see the product?</h3><p className="mt-3 text-sm leading-7 text-muted">Explore the current workspace and the workflows available to your team.</p><button className={`${action} mt-5`} onClick={onGetStarted}>Explore Provider.ai <ArrowUpRight size={16} /></button></div></div><form onSubmit={prepareEnquiry} className="grid gap-5 rounded-xl border border-line bg-white p-6 sm:p-8"><p className="rounded-lg bg-canvas p-3 text-xs leading-6 text-muted">You can prepare and copy your enquiry here. Online delivery is not connected yet.</p><label className="grid gap-2 text-sm">Your name<input name="Name" required autoComplete="name" className="workspace-field" /></label><label className="grid gap-2 text-sm">Work email<input name="Email" type="email" required autoComplete="email" className="workspace-field" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Provider name<input name="Organisation" required className="workspace-field" /></label><label className="grid gap-2 text-sm">Team size<select name="Team size" className="workspace-field"><option>1–10 workers</option><option>11–25 workers</option><option>26–50 workers</option><option>51+ workers</option></select></label></div><label className="grid gap-2 text-sm">Services, current systems and what you want to improve<textarea name="Enquiry" required rows={5} className="workspace-field py-3" /></label><button type="submit" className="primary-button">Copy enquiry <ArrowRight size={16} /></button>{notice && <p role="status" className="text-sm leading-6 text-muted">{notice}</p>}</form></section>}

    {page !== "contact" && <section className="bg-brand-100 py-16"><div className={`${wrap} flex flex-wrap items-center justify-between gap-8`}><div><h2 className={heading}>One place for your working day.</h2><p className="mt-4 text-sm leading-7 text-muted">See how Provider.ai brings your NDIS operations together.</p></div><button className={action} onClick={onGetStarted}>Explore Provider.ai <ArrowUpRight size={17} /></button></div></section>}
  </PublicShell>;
}
