import { PageHeader } from "../components/PageHeader";
import { useEffect, useState, type ReactNode } from "react";
import { Bell, Building2, Check, ChevronRight, CircleDollarSign, Database, KeyRound, Link2, LockKeyhole, RefreshCw, Save, ShieldCheck, Users, X } from "lucide-react";
import { api } from "../api";
import type { XeroConnection } from "../types";

const sections = [
  { id: "organisation", label: "Organisation", icon: Building2 },
  { id: "people", label: "Users & access", icon: Users },
  { id: "services", label: "Services & billing", icon: CircleDollarSign },
  { id: "xero", label: "Xero accounting", icon: Link2 },
  { id: "security", label: "Security", icon: LockKeyhole },
  { id: "notifications", label: "Notifications", icon: Bell },
  { id: "data", label: "Data & privacy", icon: Database },
] as const;
type SectionId = (typeof sections)[number]["id"];

export function Settings({ role, onOpenRoles }: { role: string; onOpenRoles: () => void }) {
  const [section, setSection] = useState<SectionId>("organisation");
  const [saved, setSaved] = useState(false);
  const [xero, setXero] = useState<XeroConnection>({ status: "disconnected", settings: {} });
  const [syncing, setSyncing] = useState(false);
  const [xeroError, setXeroError] = useState("");
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  useEffect(() => { api.xeroStatus().then(setXero).catch((error: Error) => setXeroError(error.message)); }, []);
  const connectXero = async () => { setXeroError(""); try { const result = await api.xeroAuthorize(); window.location.assign(result.authorizeUrl); } catch (error) { setXeroError(error instanceof Error ? error.message : "Xero connection could not start"); } };
  const disconnectXero = async () => { setXeroError(""); try { await api.xeroDisconnect(); setXero({ status: "disconnected", settings: {} }); } catch (error) { setXeroError(error instanceof Error ? error.message : "Xero could not be disconnected"); } };
  const syncXero = async () => { setSyncing(true); setXeroError(""); try { setXero(await api.xeroSync()); } catch (error) { setXeroError(error instanceof Error ? error.message : "Xero sync could not be queued"); } finally { setSyncing(false); } };

  return <section className="page settings-page m-0 min-h-[calc(100vh-73px)] w-full max-w-none px-[clamp(12px,1.5vw,24px)] pb-14 pt-8 text-[13px] leading-normal">
    <PageHeader category="Organisation" title="Settings" description="Manage your organisation, access, services and connected systems."></PageHeader>
    <div className="grid items-start gap-4 lg:grid-cols-[220px_minmax(0,850px)]">
      <nav className="rounded-xl border border-line bg-white p-2" aria-label="Company settings">{sections.map((item) => <button key={item.id} onClick={() => setSection(item.id)} className={`flex min-h-11 w-full items-center gap-3 rounded-lg border-0 px-3 text-left text-[13px] font-medium ${section === item.id ? "bg-brand-50 text-brand-800" : "bg-white text-copy hover:bg-[#f6f8fa]"}`}><item.icon className="size-[17px]" /><span className="flex-1">{item.label}</span><ChevronRight className="size-4 opacity-50" /></button>)}</nav>
      <article className="overflow-hidden rounded-xl border border-line bg-white shadow-panel">
        {section === "organisation" && <SettingsPanel title="Organisation profile" description="Legal and operating details used across documents and exports." onSave={save}><Field label="Legal organisation name"><input defaultValue="Harbour Care Services Pty Ltd" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Trading name"><input defaultValue="Harbour Care" /></Field><Field label="ABN"><input defaultValue="51 824 753 119" /></Field><Field label="Primary timezone"><select defaultValue="Australia/Adelaide"><option>Australia/Adelaide</option><option>Australia/Sydney</option><option>Australia/Brisbane</option><option>Australia/Perth</option></select></Field><Field label="Default service region"><input defaultValue="Western Sydney, NSW" /></Field></div></SettingsPanel>}
        {section === "people" && <SettingsPanel title="Users, roles and access" description="Control who can view participants, approve services, export data and administer the organisation." onSave={save}><SettingRow icon={<ShieldCheck />} title="Role-based access" copy={`${role === "owner" ? "Organisation owner" : "Organisation administrator"} · full access`} action="Manage roles" onAction={onOpenRoles} /><SettingRow icon={<Users />} title="Invitations and access reviews" copy="Review active accounts, pending invitations and access boundaries" action="Review" onAction={onOpenRoles} /><Toggle label="Require manager approval for sensitive exports" defaultChecked /><Toggle label="Limit support workers to assigned participants" defaultChecked /></SettingsPanel>}
        {section === "services" && <SettingsPanel title="Services and billing rules" description="Define what can be rostered and how delivered supports become invoice lines." onSave={save}><Toggle label="Assistance with social and community participation" defaultChecked /><Toggle label="Assistance with daily life" defaultChecked /><Toggle label="Travel and non-face-to-face claiming requires approval" defaultChecked /><div className="grid gap-4 sm:grid-cols-2"><Field label="Invoice payment terms"><select defaultValue="14 days"><option>7 days</option><option>14 days</option><option>30 days</option></select></Field><Field label="Default tax treatment"><select defaultValue="GST free"><option>GST free</option><option>GST on income</option></select></Field></div></SettingsPanel>}
        {section === "xero" && <XeroPanel connected={xero.status === "connected"} syncing={syncing} lastSync={xero.lastSyncAt ? new Date(xero.lastSyncAt).toLocaleString("en-AU") : "Not synced"} organisationName={xero.organisationName} error={xeroError || xero.lastError} onConnect={connectXero} onDisconnect={disconnectXero} onSync={syncXero} />}
        {section === "security" && <SettingsPanel title="Security and sessions" description="Organisation-wide authentication and access safeguards." onSave={save}><Toggle label="Require multi-factor authentication for administrators" defaultChecked /><Toggle label="Require step-up authentication for exports and role changes" defaultChecked /><div className="grid gap-4 sm:grid-cols-2"><Field label="Session timeout"><select defaultValue="8 hours"><option>1 hour</option><option>8 hours</option><option>12 hours</option></select></Field><Field label="Failed login lockout"><select defaultValue="5 attempts"><option>5 attempts</option><option>10 attempts</option></select></Field></div><SettingRow icon={<KeyRound />} title="Active sessions" copy="3 devices across 2 administrators" action="Review sessions" onAction={() => window.dispatchEvent(new CustomEvent("provider-notice", { detail: "Session review opened." }))} /></SettingsPanel>}
        {section === "notifications" && <SettingsPanel title="Notifications and escalation" description="Choose which operational exceptions require email or in-app attention." onSave={save}><Toggle label="Unfilled shift approaching start time" defaultChecked /><Toggle label="Worker credential expires within 30 days" defaultChecked /><Toggle label="Incident deadline or escalation" defaultChecked /><Toggle label="Claim rejected or invoice overdue" defaultChecked /><Field label="Daily operations summary"><select defaultValue="7:00 am"><option>Disabled</option><option>7:00 am</option><option>8:00 am</option></select></Field></SettingsPanel>}
        {section === "data" && <SettingsPanel title="Data, privacy and retention" description="Manage residency, retention and customer-controlled exports." onSave={save}><SettingRow icon={<Database />} title="Data region" copy="Australia · production and encrypted backups" /><Toggle label="Record sensitive views and exports in the audit log" defaultChecked /><div className="grid gap-4 sm:grid-cols-2"><Field label="Participant record retention"><select defaultValue="7 years after exit"><option>7 years after exit</option><option>10 years after exit</option></select></Field><Field label="Audit log retention"><select defaultValue="7 years"><option>7 years</option><option>10 years</option></select></Field></div><SettingRow icon={<Database />} title="Organisation data export" copy="Creates a permission-checked, audited export package" action="Request export" onAction={() => window.dispatchEvent(new CustomEvent("provider-notice", { detail: "Data export request recorded for administrator approval." }))} /></SettingsPanel>}
      </article>
    </div>
    {saved && <div className="action-toast" role="status"><Check className="size-4 text-positive" />Settings saved</div>}
  </section>;
}

function SettingsPanel({ title, description, onSave, children }: { title: string; description: string; onSave: () => void; children: ReactNode }) { return <><header className="border-b border-line px-5 py-4"><h2 className="m-0 text-[18px] font-semibold">{title}</h2><p className="mb-0 mt-1 text-[13px] text-muted">{description}</p></header><div className="grid gap-4 p-5">{children}</div><footer className="flex justify-end border-t border-line bg-[#f7f7f4] px-5 py-3"><button className="primary-button min-h-11" onClick={onSave}><Save className="size-4" />Save changes</button></footer></>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1.5 text-[12px] font-semibold text-copy [&_input]:min-h-11 [&_input]:border [&_input]:px-3 [&_select]:min-h-11 [&_select]:border [&_select]:px-3">{label}{children}</label>; }
function Toggle({ label, defaultChecked = false }: { label: string; defaultChecked?: boolean }) { return <label className="flex min-h-12 items-center gap-3 rounded-lg border border-line px-4 text-[13px] font-medium"><input type="checkbox" defaultChecked={defaultChecked} className="size-4" />{label}</label>; }
function SettingRow({ icon, title, copy, action, onAction }: { icon: ReactNode; title: string; copy: string; action?: string; onAction?: () => void }) { return <div className="grid min-h-16 grid-cols-[36px_1fr_auto] items-center gap-3 rounded-lg border border-line p-3"><span className="grid size-9 place-items-center rounded-lg bg-brand-50 text-brand-700">{icon}</span><span><strong className="block text-[13px]">{title}</strong><small className="mt-1 block text-[12px] text-muted">{copy}</small></span>{action && onAction && <button className="secondary-button" onClick={onAction}>{action}</button>}</div>; }
function XeroPanel({ connected, syncing, lastSync, organisationName, error, onConnect, onDisconnect, onSync }: { connected: boolean; syncing: boolean; lastSync: string; organisationName?: string; error?: string; onConnect: () => void; onDisconnect: () => void; onSync: () => void }) { return <><header className="border-b border-line px-5 py-4"><div className="flex items-center justify-between gap-3"><div><h2 className="m-0 text-[18px] font-semibold">Xero accounting</h2><p className="mb-0 mt-1 text-[13px] text-muted">Send approved billing to Xero and reconcile payment status back into Provider.ai.</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${connected ? "bg-positive/10 text-positive" : "bg-[#eef1f4] text-muted"}`}>{connected ? "Connected" : "Not connected"}</span></div></header><div className="grid gap-4 p-5">{error && <div role="alert" className="rounded-lg border border-danger/20 bg-danger/5 p-3 text-[12px] text-danger">{error}</div>}<div className="rounded-lg border border-brand-200 bg-brand-50 p-4"><strong className="text-[13px] text-brand-900">What happens after connection</strong><ol className="mb-0 mt-3 grid gap-2 pl-5 text-[12px] leading-5 text-copy"><li>Approved payer records become Xero contacts.</li><li>Approved invoices and credit notes are sent once with duplicate protection.</li><li>Xero payments return to Provider.ai for reconciliation.</li><li>Rejected or unmatched records stay visible in Finance for resolution.</li></ol></div><div className="grid gap-3 sm:grid-cols-3"><Fact label="Provider.ai owns" value="Shifts, visits, notes and claim evidence" /><Fact label="Xero organisation" value={organisationName ?? (connected ? "Connected organisation" : "Not connected")} /><Fact label="Last sync" value={lastSync} /></div>{connected && <><Toggle label="Sync approved invoices automatically" defaultChecked /><Toggle label="Create Xero contacts from approved payer records" defaultChecked /><Toggle label="Import payments for reconciliation" defaultChecked /></>}<div className="flex flex-wrap gap-2">{connected ? <><button className="primary-button min-h-11" onClick={onSync} disabled={syncing}><RefreshCw className={`size-4 ${syncing ? "animate-spin" : ""}`} />{syncing ? "Queuing sync" : "Sync now"}</button><button className="secondary-button min-h-11 text-danger" onClick={onDisconnect}><X className="size-4" />Disconnect</button></> : <button className="primary-button min-h-11" onClick={onConnect}><Link2 className="size-4" />Connect Xero organisation</button>}</div></div></>; }
function Fact({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-line bg-[#f7f7f4] p-3"><small className="text-[11px] text-muted">{label}</small><strong className="mt-1 block text-[12px] leading-5">{value}</strong></div>; }
