import { useState, type ReactNode } from "react";
import { AlertTriangle, ArrowLeft, CalendarDays, CheckCircle2, ClipboardList, FileText, Mail, Pencil, Phone, Plus, ShieldCheck, Target, UsersRound, WalletCards, X } from "lucide-react";
import { participants } from "../../../mocks/mockDomain";
import { formatMoney as money } from "../../../utils/formatters";
import { avatarToneClass } from "../../../utils/tailwind";

type Participant = (typeof participants)[number];
type Drawer = "profile" | "contact" | "consent" | "worker" | "matching" | "note" | "document" | null;
const tabs = ["Overview", "Supports & goals", "Plan & funding", "Support workers", "People & contacts", "Notes", "Documents", "Compliance"];

export function ParticipantRecord({ participant, tab, setTab, onBack }: { participant: Participant; tab: string; setTab: (value: string) => void; onBack: () => void }) {
  const [drawer, setDrawer] = useState<Drawer>(null);
  const utilisation = Math.round((participant.used / participant.budget) * 100);
  const firstName = participant.name.split(" ")[0];
  const navigateRoster = () => window.dispatchEvent(new CustomEvent("provider-navigate", { detail: "roster" }));
  return <section className="page module-page participant-record">
    <button className="mb-5 inline-flex min-h-11 items-center gap-2 border-0 bg-transparent text-[13px] font-semibold text-brand-700" onClick={onBack}><ArrowLeft className="size-4" />All participants</button>
    <header className="grid grid-cols-[64px_minmax(0,1fr)_auto] items-center gap-4 max-md:grid-cols-[52px_minmax(0,1fr)]">
      <span className={`grid size-16 place-items-center rounded-xl text-base font-bold max-md:size-12 ${avatarToneClass(participant.colour)}`}>{participant.initials}</span>
      <div><p className="eyebrow">Participant record</p><h1>{participant.name}</h1><p className="mt-1 text-sm text-muted">{participant.pronouns} · NDIS {participant.ndis} · {participant.location}</p><div className="mt-3 flex gap-2"><Status>{participant.status}</Status><Status tone={participant.risk === "High" ? "danger" : participant.risk === "Medium" ? "warning" : "positive"}>{participant.risk} risk</Status></div></div>
      <div className="flex gap-2 max-md:col-span-2"><a className="secondary-button min-h-11 no-underline" href="tel:+61412555010"><Phone className="size-4" />Call</a><a className="secondary-button min-h-11 no-underline" href={`mailto:${firstName.toLowerCase()}@example.com`}><Mail className="size-4" />Email</a><button className="secondary-button min-h-11" onClick={() => setDrawer("profile")}><Pencil className="size-4" />Edit</button></div>
    </header>
    <nav className="my-6 flex overflow-x-auto border-b border-line" aria-label="Participant record sections">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`min-h-11 shrink-0 border-0 border-b-2 px-3 text-[12px] font-semibold ${tab === item ? "border-brand-600 bg-brand-50/50 text-brand-800" : "border-transparent bg-transparent text-muted hover:text-ink"}`}>{item}</button>)}</nav>

    {tab === "Overview" && <div className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(280px,.55fr)]"><main className="grid content-start gap-4">
      <Card title={`About ${firstName}`} action="Edit profile" onAction={() => setDrawer("profile")}><p className="m-0 text-sm leading-6 text-muted">{firstName} enjoys community activities, predictable routines and being involved in decisions. Use clear language, allow processing time and confirm changes before each shift.</p><dl className="mt-5 grid grid-cols-2 gap-3 max-sm:grid-cols-1"><Fact label="Preferred communication" value="Clear verbal prompts and written choices" /><Fact label="Service region" value="Western Sydney" /><Fact label="Primary address" value={`12 Example Street, ${participant.location} NSW`} /><Fact label="Plan management" value={participant.plan} /></dl></Card>
      <Card title="Upcoming supports" action="Open roster" onAction={navigateRoster}>{["Today · 8:00–11:00 am", "Tuesday · 1:00–4:00 pm", "Thursday · 9:30–11:30 am"].map((time, index) => <RecordRow key={time} icon={<CalendarDays />} title={["Daily personal activities", "Community participation", "Capacity building"][index]} meta={`${time} · ${index === 1 ? "Jack Harris" : "Ava Williams"}`} value="Confirmed" onClick={navigateRoster} />)}</Card>
    </main><aside className="grid content-start gap-4"><Card title="Plan utilisation" action="View funding" onAction={() => setTab("Plan & funding")}><strong className="text-2xl">{utilisation}%</strong><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#edf0f3]"><i className="block h-full bg-brand-600" style={{ width: `${utilisation}%` }} /></div><p className="mb-0 mt-3 text-xs text-muted">{money(participant.budget - participant.used)} remaining</p></Card><Card title="Important care information"><InfoRow warning title="Communication preference" copy="Allow processing time and offer simple choices." /><InfoRow title="Restrictive practices" copy="None recorded · reviewed 18 July 2026." /></Card></aside></div>}

    {tab === "Supports & goals" && <Section title="Participant goals" description="Outcomes linked to delivered supports and reviewed notes." action="Add goal" onAction={() => setDrawer("note")}>{["Build confidence participating in the community", "Develop independence with daily routines", "Strengthen social connections"].map((goal, index) => <RecordRow key={goal} icon={<Target />} title={goal} meta={`${[7,4,2][index]} activities recorded this month`} value={`${[68,54,72][index]}%`} onClick={() => setDrawer("note")} />)}</Section>}
    {tab === "Plan & funding" && <Section title="Current NDIS plan" description="Funding periods and service agreement coverage."><div className="grid gap-3 sm:grid-cols-3"><Fact label="Management" value={participant.plan} /><Fact label="Total budget" value={money(participant.budget)} /><Fact label="Available" value={money(participant.budget - participant.used)} /></div><button className="secondary-button mt-5" onClick={() => setDrawer("document")}><FileText className="size-4" />Open service agreement</button></Section>}
    {tab === "Support workers" && <Section title="Assigned support workers" description="Eligibility and participant preferences are checked before assignment." action="Assign worker" onAction={() => setDrawer("worker")}>{["Ava Williams", "Jack Harris", "Amelia Taylor", "Liam Smith"].map((name, index) => <RecordRow key={name} icon={<UsersRound />} title={name} meta={index < 2 ? "Preferred worker · credentials current" : "Assigned · credentials current"} value={index < 2 ? "Preferred" : "Assigned"} onClick={() => setDrawer("worker")} />)}<button className="secondary-button mt-4" onClick={() => setDrawer("matching")}><ShieldCheck className="size-4" />Review matching preferences</button></Section>}
    {tab === "People & contacts" && <Section title="People and contacts" description="Information sharing follows the participant’s current consent." action="Add contact" onAction={() => setDrawer("contact")}>{[participant.coordinator, "Sophie Carter", "James Carter", "Dr Priya Nair"].map((name, index) => <RecordRow key={name} icon={<Phone />} title={name} meta={["Support coordinator", "Plan nominee · emergency contact", "Approved family contact", "General practitioner"][index]} value={index < 2 ? "Primary" : "Contact"} onClick={() => setDrawer("contact")} />)}<button className="secondary-button mt-4" onClick={() => setDrawer("consent")}><ShieldCheck className="size-4" />Review consent</button></Section>}
    {tab === "Notes" && <Section title="Progress notes" description="Reviewed records linked to shifts and participant goals." action="Add note" onAction={() => setDrawer("note")}><RecordRow icon={<ClipboardList />} title="Community participation progress" meta="Ava Williams · today at 11:18 am" value="Approved" onClick={() => setDrawer("note")} /><RecordRow icon={<ClipboardList />} title="Daily living support" meta="Jack Harris · 2 September" value="Approved" onClick={() => setDrawer("note")} /></Section>}
    {tab === "Documents" && <Section title="Participant documents" description="Versioned records with controlled access." action="Add document" onAction={() => setDrawer("document")}><RecordRow icon={<FileText />} title="Service agreement v3" meta="Approved · expires 30 June 2027" value="PDF" onClick={() => setDrawer("document")} /><RecordRow icon={<FileText />} title="Communication support plan" meta="Reviewed 18 July 2026" value="PDF" onClick={() => setDrawer("document")} /></Section>}
    {tab === "Compliance" && <Section title="Consent, risk and evidence" description="Current safeguards and review history."><RecordRow icon={<ShieldCheck />} title="Information sharing consent" meta="Confirmed 12 June 2026" value="Current" onClick={() => setDrawer("consent")} /><RecordRow icon={<AlertTriangle />} title="Participant risk assessment" meta="Next review 10 October 2026" value={participant.risk} onClick={() => setDrawer("consent")} /></Section>}

    {drawer && <DrawerPanel title={drawerTitle(drawer)} onClose={() => setDrawer(null)} />}
  </section>;
}

function Card({ title, action, onAction, children }: { title: string; action?: string; onAction?: () => void; children: ReactNode }) { return <section className="rounded-xl border border-line bg-white p-5 shadow-panel"><header className="mb-4 flex items-start justify-between gap-4"><h2 className="m-0 text-base font-semibold">{title}</h2>{action && onAction && <button className="border-0 bg-transparent text-xs font-semibold text-brand-700" onClick={onAction}>{action}</button>}</header>{children}</section>; }
function Section({ title, description, action, onAction, children }: { title: string; description: string; action?: string; onAction?: () => void; children: ReactNode }) { return <section className="rounded-xl border border-line bg-white shadow-panel"><header className="flex items-end justify-between gap-4 border-b border-line p-5 max-sm:items-start"><div><h2 className="m-0 text-lg font-semibold">{title}</h2><p className="mb-0 mt-1 text-sm text-muted">{description}</p></div>{action && onAction && <button className="primary-button min-h-11 shrink-0" onClick={onAction}><Plus className="size-4" />{action}</button>}</header><div className="p-5">{children}</div></section>; }
function RecordRow({ icon, title, meta, value, onClick }: { icon: ReactNode; title: string; meta: string; value: string; onClick: () => void }) { return <button onClick={onClick} className="grid min-h-[68px] w-full grid-cols-[38px_minmax(0,1fr)_auto] items-center gap-3 border-0 border-b border-line bg-white text-left last:border-b-0 hover:bg-[#f7f7f4]"><span className="grid size-9 place-items-center rounded-lg bg-brand-50 text-brand-700">{icon}</span><span className="min-w-0"><strong className="block truncate text-[13px]">{title}</strong><small className="mt-1 block truncate text-xs text-muted">{meta}</small></span><Status>{value}</Status></button>; }
function Fact({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-line bg-[#f7f7f4] p-3"><dt className="text-[11px] font-medium text-muted">{label}</dt><dd className="mb-0 ml-0 mt-1 text-[13px] font-semibold text-ink">{value}</dd></div>; }
function Status({ children, tone = "brand" }: { children: ReactNode; tone?: "brand" | "positive" | "warning" | "danger" }) { const colours = { brand: "bg-brand-50 text-brand-800", positive: "bg-positive/10 text-positive", warning: "bg-warning/10 text-warning", danger: "bg-danger/10 text-danger" }; return <span className={`w-fit rounded-full px-2 py-1 text-[11px] font-semibold ${colours[tone]}`}>{children}</span>; }
function InfoRow({ title, copy, warning = false }: { title: string; copy: string; warning?: boolean }) { return <div className="flex gap-3 border-t border-line py-3 first:border-t-0"><span className={`grid size-8 shrink-0 place-items-center rounded-lg ${warning ? "bg-warning/10 text-warning" : "bg-positive/10 text-positive"}`}>{warning ? <AlertTriangle className="size-4" /> : <CheckCircle2 className="size-4" />}</span><span><strong className="text-[13px]">{title}</strong><small className="mt-1 block text-xs text-muted">{copy}</small></span></div>; }
function DrawerPanel({ title, onClose }: { title: string; onClose: () => void }) { return <div className="fixed inset-0 z-[120] bg-ink/35" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="absolute inset-y-0 right-0 flex w-full max-w-[500px] flex-col border-l border-line bg-white shadow-float"><header className="flex items-start justify-between border-b border-line p-6"><div><p className="eyebrow">Participant workflow</p><h2 className="m-0 text-xl font-semibold">{title}</h2><p className="mt-2 text-sm text-muted">Changes are attributed to your account and appear in record history.</p></div><button className="icon-button" onClick={onClose} aria-label="Close drawer"><X className="size-4" /></button></header><form className="grid flex-1 content-start gap-5 overflow-y-auto p-6" onSubmit={(event) => { event.preventDefault(); onClose(); window.dispatchEvent(new CustomEvent("provider-notice", { detail: `${title} saved.` })); }}><label className="grid gap-2 text-sm font-medium">Record title<input required className="min-h-11 border px-3" placeholder="Enter a clear title" /></label><label className="grid gap-2 text-sm font-medium">Details<textarea required className="min-h-32 border p-3" placeholder="Record the information needed for this workflow…" /></label><label className="flex items-start gap-3 rounded-lg border border-line p-4 text-sm"><input type="checkbox" required className="mt-1 size-4" /><span><strong className="block">I have checked this information</strong><small className="mt-1 block text-muted">Human review is required before saving.</small></span></label><footer className="flex justify-end gap-2"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit">Save record</button></footer></form></aside></div>; }
function drawerTitle(drawer: Exclude<Drawer, null>) { return ({ profile: "Edit participant", contact: "Contact record", consent: "Consent and risk review", worker: "Worker assignment", matching: "Matching preferences", note: "Progress record", document: "Document record" })[drawer]; }
